### ISSUE TITLE
Basic Setup incomplete?

### ISSUE THREAD

**Issue by subsoap** [rgrams/rendercam#1]
Following the two steps in a blank project produces this error

```
ERROR:SCRIPT: /rendercam/rendercam.lua:241: attempt to index upvalue 'curCam' (a nil value)
stack traceback:
	/rendercam/rendercam.lua:241: in function 'update_window'
	/rendercam/rendercam.render_script:12: in function 'update_window'
	/rendercam/rendercam.render_script:78: in function </rendercam/rendercam.render_script:72>
```

**Comment by rgrams** [comment]
Hmm, that means there's no active camera. Did the "active" property checkbox get un-checked somehow?

**Comment by subsoap** [comment]
Hmm... I tested again and it's working now. Not sure what happened before. Only thing different is updated version of editor 2. I tested unchecking active and it didn't cause it to bug out.

**Comment by rgrams** [comment]
Hmm, very strange. Rereading your error log I realize the error is happening at a different point that I thought. It looks like the render script must have gotten a "window_resized" message before the camera was init (but that's not the order I got in my tests). I'll see about adding a check for that. 

You don't get any errors if there is no active camera?! I don't know how that would happen either, sheesh.

**Comment by subsoap** [comment]
Second time I tested I realize I forgot to set the render script to be active. Testing again with it active does produce the errors again.

```
ERROR:SCRIPT: /rendercam/rendercam.lua:217: attempt to index upvalue 'curCam' (a nil value)
stack traceback:
	/rendercam/rendercam.lua:217: in function 'calculate_view'
	/rendercam/rendercam.render_script:31: in function </rendercam/rendercam.render_script:29>
```
The collection that's active has no other script except for the camera go's script.

I also realized what's probably missing - enabling shared script state in the game.project file. Enabling that makes it work!

**Comment by rgrams** [comment]
Ahhh. Yup it's the shared script setting, good find!

**Comment by rgrams** [comment]
OK, I added a check for the shared_state setting and an error log if there's no active camera too. Closing this, reopen it if you still have issues, and thanks for the debugging!
