### ISSUE TITLE
Doesn't work in small resolutions?

### ISSUE THREAD

**Issue by subsoap** [rgrams/rendercam#10]
Testing in 320x240 project and seems to break? Still testing...

**Comment by subsoap** [comment]
With previous settings I was using for a larger screen project it wasn't working, but with fixed aspect ratio set it is working.

**Comment by rgrams** [comment]
What "breaks" exactly?

**Comment by subsoap** [comment]
It is not constraining to the view, allows the height and width of the 320x240 view to be clipped. I can get example soon.

**Comment by subsoap** [comment]
Looking back this is probably because of a lack of  Use View Area but who knows. Probably user error.
