### ISSUE TITLE
render.enable_state(render.STATE_CULL_FACE) cause a problem with physic debug

### ISSUE THREAD

**Issue by selimanac** [rgrams/rendercam#14]
I don't know why but line 52 on rendercam.render_script cause physic debug draw to disappear. When I remove this line, physic debug draw works as expected on build. 

With line 52
![screen shot 2018-01-18 at 17 02 07](https://user-images.githubusercontent.com/1324635/35101658-5c06c738-fc71-11e7-96ea-45f985073184.png)

without
![screen shot 2018-01-18 at 17 01 41](https://user-images.githubusercontent.com/1324635/35101657-5be36a18-fc71-11e7-894e-56a61aa4a9cb.png)

**Comment by rgrams** [comment]
Wow, I can't believe I missed this, thanks for reporting! Fixed in 74195a5b758527007610acee2dc499a1aee2eace
