### ISSUE TITLE
No function to transform screen to world coordinates when using Fixed Area/Width/Height mode

### ISSUE THREAD

**Issue by ApothemBill** [rgrams/rendercam#23]
I see that rendercam does not have a function to transform screen coordinates to world coordinates when using Fixed Area, Fixed Width, or Fixed Height mode. I got around this in my game that uses Fixed Height mode by adding this code, but it would be nice if there was an already built function for this (at least for orthographic mode):

```lua
local VIEW_WIDTH = 640
local VIEW_HEIGHT = 960
local WINDOW_UPDATE = hash("window_update")

function on_input(self, action_id, action)
	-- transform action.x to world coordinates
	-- action.y is already correct with Fixed Height mode
	action.x = action.x * self.x_scale + self.x_offset
	...
end

function init(self)
        ...
	self.x_scale = 1
	self.x_offset = 0
	self.url = msg.url()
	rendercam.add_window_listener(self.url)
end

function final(self)
	rendercam.remove_window_listener(self.url)
end

function on_message(self, message_id, message, sender)
	if message_id == WINDOW_UPDATE then
		self.x_scale = message.aspect * VIEW_HEIGHT/VIEW_WIDTH
		self.x_offset = -(VIEW_HEIGHT*message.aspect - VIEW_WIDTH) / 2
	end
end
```

**Comment by rgrams** [comment]
Did you try `rendercam.screen_to_world_2d()` and it did not work? That should work fine regardless of your camera mode, (and as far as I have tested, it does). Note that you need to give it `action.screen_x` and `action.screen_y` or the result will be wrong if you change the window size.

**Comment by ApothemBill** [comment]
Oh, that was it. I needed to use action.screen_x and action.screen_y, not action.x and action.y. Never mind then.

**Comment by rgrams** [comment]
OK, great.
