### ISSUE TITLE
Initialisation order

### ISSUE THREAD

**Issue by john-cheesman** [rgrams/rendercam#27]
I was having an issue with `rendercam.follow()`. I was calling it from my player script's init function expecting the camera in the same collection to follow the player object. After debugging I realised that my player was being initialised before the camera, so the default camera was receiving the follow target, not the actual camera instance.

I've read up on the [lifecycle](https://www.defold.com/manuals/application-lifecycle/) and it seems there is no way to predict or influence the order game objects are loaded in a collection. The obvious solution is to expose public functions via messages, which are handled after initialisation. However I realise this would mean fundamental API changes, you'd have to do it for all public functions.

The other option might be to expose `follows` as a property so that it can be set in advance, similar to the orthographic camera library.

Have you had to deal with this issue before?

**Comment by rgrams** [comment]
Hey, sorry for the slow reply! 

Yes, this is definitely a recurring issue. One trick is to have your script send a message to itself on init, and call `rendercam.follow()` in that message response. It feels a bit inelegant, but it works perfectly. The message is guaranteed to be received after everything is init. 

The other option is to switch to the Rendercam ["2.0 beta" branch](https://github.com/rgrams/rendercam/tree/2.0Beta), where I did add support for a 'follow' message. 

[Documentation about the follow message](https://github.com/rgrams/rendercam/tree/2.0Beta#follow--target_id-allowmultifollow-) (it's essentially identical to the function). 

Dependency link:
> https://github.com/rgrams/rendercam/archive/2.0Beta.zip

Unfortunately I haven't gotten around to making a proper changelog and release for this version yet. There shouldn't be any breaking changes, just a couple additions: follow message, follow deadzone, and camera bounds.

**Comment by john-cheesman** [comment]
That's what I've got at the minute, posting a message to itself. I'm already using version 2 for the bounds, which is working great so far. Didn't see the follow message though, will give that a go.

Thanks

**Comment by john-cheesman** [comment]
That's working, thanks
