### ISSUE TITLE
render.draw_debug2d is deprecated and will be removed in future versions, please use render.draw_debug3d instead.

### ISSUE THREAD

**Issue by subsoap** [rgrams/rendercam#30]
Probably just needs to be swapped over?

**Comment by rgrams** [comment]
Ah, good to know, I didn't see this update yet. Yeah, it will just need to be swapped. There _is_ a call to draw_debug3d in the render script now, but it's probably not in the right place.

**Comment by rgrams** [comment]
OK, updated the render script with this and a couple other tweaks, across all branches. Made a new v1.01 release from the v1.0 branch. 

https://github.com/rgrams/rendercam/archive/v1.0.1.zip
