### ISSUE TITLE
Options for repeating texture instead of black bars

### ISSUE THREAD

**Issue by subsoap** [rgrams/rendercam#4]
Like this

![2017-11-07 18_53_23-nuclear throne](https://user-images.githubusercontent.com/409170/32529355-f1ff7cc0-c3ec-11e7-8315-b3472ee51d48.png)

Could be done a number of ways... have a uniformly scaled up quad to fit the large either height or width. Then adjust the uvs of the quad's material to be at the correct scale factor of the scale size. Then make the quad's render predicate draw where the black would.

Then can let the user set a uv offset so that over time their repeating background can move for example slowly at a diagonal (you've probably seen that in some games especially Japanese).

Btw I can make pull requests for these features at some point just not right now but if you are happy to implement them then super great ⭐⭐⭐⭐⭐.

**Comment by rgrams** [comment]
This is definitely something that should be included, and I thought about it before, but didn't think of a good way to do it. I thought it might be easiest to just place big sprites/gui nodes on the sides and _not_ use a fixed aspect ratio. Depending on the game, that would add that much extra overdraw though. 

It needs to support [static images on either side](https://i.ytimg.com/vi/hoksEjGzVhI/maxresdefault.jpg) (and I guess top and bottom too), as well as repeating textures. Ideally they would be normal sprites or GUI nodes so people would have full control over the material, so they could easily do a scrolling effect on their own. 

Actually, now that I think about it, drawing GUI on top of the black bars seems like the best option. Same as the hack solution I thought of before, but no overdraw. A lot of these games have GUI outside the camera view area too. [The Hurricane of the Varstray](http://cdn.edgecast.steamstatic.com/steam/apps/416380/ss_3358587262b552265824edf61640faedc48d32c5.1920x1080.jpg?t=1493825896), [Downwell](http://cdn.edgecast.steamstatic.com/steam/apps/360740/ss_eaab64c0e734e568912fa3ff435e7bd09a28f70b.1920x1080.jpg?t=1498680256) Now I'm just thinking out loud . . .

**Comment by rgrams** [comment]
OK, I changed it so GUIs render on top of the black bars, over the full window. That shouldn't break anything, it just means things won't be cropped. I also added a window update listener feature and a `screen_to_gui` transform function that make it easy to stretch GUI nodes to fit the black bar areas, if that's what you want. 

I didn't manage to make a tiling shader that works how I want. If you have any ideas on that, let me know. I found a couple forum threads about it ([link](https://forum.defold.com/t/tiled-textures-for-sprites-gui-boxes/2289), [link](https://forum.defold.com/t/tiling-gui-textures-possible/293)), but they didn't get much of anywhere. It was easy to make something tile based on screen coordinates, but that means the cutoff point is arbitrary, and it doesn't look so good. (and it doesn't scale with the window size)
![screenshot 2017-11-09 08 26 49](https://user-images.githubusercontent.com/11370192/32619155-d809e84e-c547-11e7-9cd1-a3b9d75917b8.png)

If we could solve that, this issue would be closed.

**Comment by subsoap** [comment]
Check the scrolling texture example here? https://github.com/subsoap/deffx https://github.com/subsoap/deffx/blob/master/deffx/materials/sprite/scrolling.fp

**Comment by rgrams** [comment]
Yeah, I was trying to do something fancy where it would tile irrespective of scaling and outward from the node origin, but I think that requires the model matrix, and some much fancier shader work. If I every figure it out I'll link it in the readme or something. 

It's easy enough to just make the GUI nodes large enough to cover all real-world scenarios, so I'm closing this.
