### ISSUE TITLE
Number of fields causing crash

### ISSUE THREAD

**Issue by Learningtotry** [rgrams/rendercam#44]
When I try the rendercam, I get this error:
```
 /rendercam/camera.script:145: vmath.vector4 only has fields x, y, z, w.
stack traceback:
	[C]: in function '__index'
```

**Comment by rgrams** [comment]
Hmm, that's quite strange. Line 145 in camera.script is just this:
> `self.data.lpos = go.get_position()`

What dependency link do you have in your game.project?
Did you modify any of the rendercam files at all?

**Comment by Learningtotry** [comment]
I did not modify anything until this error first appeared. Since it has appeared I have tried debugging with print statements such as print(go.get_position()), print(self.data.lpos) the second print statement actually caused an error once! I checked and that line you gave is the same in my code, unaltered.

**Comment by Learningtotry** [comment]
Does it somehow think that self.data is a vector instead of a container? That would explain why it says vmath.vector4 only has fields x, y, z, w. However, it outputs a table in hexadecimal when I put it in a print function. I have tried debugging with 

function on_message(self, message_id, message, sender)
	if message_id == hash("post-update") then
		-- have to update pos after update or it jitters like crazy
		print(self.data)
		print(self.data.lpos)
		print("my pos is ", go.get_position())
		-- Update transform stuff
		self.data.lpos = go.get_position()
But the go.get_position() statement is not printed

**Comment by rgrams** [comment]
Very very strange. I'm sorry you're having this problem, I've never heard of anything like this before. Is it possible for you to zip up your project and send it to me? Either attach it here, or [send me](https://forum.defold.com/u/ross.grams/) a message with it on the forum? 

>Does it somehow think that self.data is a vector instead of a container?

Yes, that's what it sounds like. You should only get that error when trying to set a specific key on a vector4. Maybe it's getting overwritten somewhere by mistake. This is the first error you get in the console, right? There aren't any others before?

**Comment by Learningtotry** [comment]
[Zipped.zip](https://github.com/rgrams/rendercam/files/4724865/Zipped.zip)
Here is the file I have tried to zip.

**Comment by Learningtotry** [comment]
While you're here, what do you think is the best way to learn a programming language?

**Comment by rgrams** [comment]
OK, thanks a lot for the project. 
The first thing I tried was removing your player.script from the scene. That solved the problem, there were no errors after that.

The problem was in your init function, this line:
> `go = vmath.vector4(0, 0, 0, 0)`

You're defining a global variable, 'go' that is a vector4. 
Defold uses 'go' as the namespace (or module name) for all the game object functions. Like go.get_position(), go.set_position(), etc. So when you set 'go' as a global variable, you overwrite all those functions! :D

You should be very careful about setting global variables. Always use `local` when you initialize a variable name (including your functions!).

**Comment by rgrams** [comment]
As for learning a programming language, hmm...haha, that's a big question.

First of all, most programming languages are mostly the same. They may each use slightly different symbols for things, but in general they are very similar. They all have variables, types, functions, "scope", etc. So it's really about learning, "programming", not learning one language in particular. 

Anyway, for learning I think it's best to alternate between very "boring" studying (reading books and following basic exercises), and more "fun" experimenting on your own. 
- Too much "boring" studying, and you will lose interest.
- Too much "fun" experimenting and you will never learn anything properly.

**For the "boring" part:**
Defold's lua manual is a very good overview to start with: https://defold.com/manuals/lua/
After that, start going through Programming in Lua, chapter by chapter: http://www.lua.org/pil/contents.html (and type in and run all the code yourself.)

**For the "fun" part:**
Play around with Defold! Keep it small. Try lots of different little tiny things so you get experience. Don't just copy-paste one piece of code that works, or you won't learn anything. Try re-creating the Defold examples yourself: https://defold.com/examples/basics/simple_move/ Maybe try making a small program that could be useful in real life, like a calculator or alarm clock or something. Just for fun.

**Comment by Learningtotry** [comment]
When I first started programming, I just copied the code I saw. Since then I have stopped that. I have already started going through the Lua tutorial. I think one point which has helped me a lot so far is that I once read a book on programming logic and design. Thanks for the help!
