### ISSUE TITLE
Default camera fallback?

### ISSUE THREAD

**Issue by rgrams** [rgrams/rendercam#6]
Currently, Rendercam requires that you have an active camera at all times, it logs errors if you don't. Maybe this isn't the ideal behavior though. There may be short periods of time when you don't care about the camera—a frame or two between loading proxies, in an initial loader collection, etc. 

So I'm thinking about adding in a default fallback camera that it will use if no cameras are active. However:
* I don't want users to be confused and not realize that their camera isn't active.
* I don't want to spam the log with warnings if the user is fully aware that there is no active camera.

Options:
* Log all the warnings I want, but have a "debug" property on the Rendercam module that the user can turn off if they don't want to see the warnings. 
* Log only one warning if there is no active camera on init but be silent for any subsequent lapses. 
* Have no warning, just use the default view/projection if there is no camera, like the default render script does. 

Any feedback on this is appreciated.

**Comment by subsoap** [comment]
Having one debug print saying that no user camera was found so default camera is being used should be fine.

**Comment by rgrams** [comment]
Thanks, that's what I did then. Closed by a5d320f17a454ad0c8acbd3e5811bf4dd984cc88
